server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: clockin-record
  datasource:
    url: jdbc:mysql://localhost:3306/clockin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: true

# OpenAPI 配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.clockin.record.controller

# 日誌配置
logging:
  level:
    root: INFO
    com.clockin: DEBUG
    org.hibernate.SQL: DEBUG
    # 顯示 JPA 查詢參數值
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # Feign 日誌
    com.clockin.record.service: DEBUG

# JWT 配置
jwt:
  secret: ClockInAuthSecretKey2025@ziv
  expiration: 86400

# 打卡配置
clock-in:
  default-timezone: Asia/Shanghai
  statistics:
    auto-calculate: true
  notification:
    enabled: true
    mail:
      enabled: false
    sms:
      enabled: false
  # 異常打卡提醒閾值
  threshold:
    late-minutes: 10
    early-leave-minutes: 10
  auth:
    baseUrl: http://localhost:8081
  admin:
    baseUrl: http://localhost:8083

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true

# Feign 客戶端配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true
